### ISSUE TITLE
Добавить колонку "Рабочих дней"

### ISSUE THREAD

**Issue by for7raid** [for7raid/HappyVacations#1]
Добавить колонку в конец таблицы и поле в индивидуальном блоке, в котором выводить количество рабочих дней по человеку в выбранном периоде. Функция GetWorkDays из VacationCalculatorService.
Нужно для планирования задач

**Comment by for7raid** [comment]
Блин. функция GetWorkDays работает только с одним месяцем, соответственно если период отображения не кратен месяцу, она работает неправильно. надо сделать ее перезагрузку еще и с параметром End

**Comment by AntonDashevsky** [comment]
Нажо обсудить, не понимаю что перегрузка даст, если end нигде внутри не используется

**Comment by for7raid** [comment]
у нас есть потребность посчитать рабочие дни в двух случаях: за любой произвольный период (колонка Рабочих дней) и за определенный месяц (для индекса зп).
`GetWorkDaysInPeriod(DateTime start, DateTime end)` и `GetWorkDaysInMonth(DateTime month)`.

при этом очевидно, что GetWorkDaysInMonth это всего-лишь частный случай GetWorkDaysInPeriod, в в котором start - это 1 число месяца, а end - последнее. Таким образом можно реализовать функцию GetWorkDaysInPeriod, и вызывать ее из GetWorkDaysInMonth, правильно посчитав end по переданному month.

```
GetWorkDaysInMonth(DateTime month) {
var end = month.AddMonth(1).AddDays(-1);
return GetWorkDaysInPeriod(month, end);
}
```
осталось только поменять вызовы в коде по нужным местам.
Сейчас ошибка в колонке Рабочих дней, она считает дни только первого месяца выбранного периода, а должна очевидно за весь период.
